# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNames = channel.unary_unary(
                '/pb.API/ListNames',
                request_serializer=api__pb2.ListNamesRequest.SerializeToString,
                response_deserializer=api__pb2.ListNamesResponse.FromString,
                )
        self.ListStat = channel.unary_unary(
                '/pb.API/ListStat',
                request_serializer=api__pb2.ListStatRequest.SerializeToString,
                response_deserializer=api__pb2.ListStatResponse.FromString,
                )
        self.ListHist = channel.unary_unary(
                '/pb.API/ListHist',
                request_serializer=api__pb2.ListHistRequest.SerializeToString,
                response_deserializer=api__pb2.ListHistResponse.FromString,
                )
        self.getPrice = channel.unary_unary(
                '/pb.API/getPrice',
                request_serializer=api__pb2.PriceRequest.SerializeToString,
                response_deserializer=api__pb2.PriceResponse.FromString,
                )
        self.getStaticData = channel.unary_unary(
                '/pb.API/getStaticData',
                request_serializer=api__pb2.StaticDataRequest.SerializeToString,
                response_deserializer=api__pb2.StaticDataResponse.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStaticData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNames,
                    request_deserializer=api__pb2.ListNamesRequest.FromString,
                    response_serializer=api__pb2.ListNamesResponse.SerializeToString,
            ),
            'ListStat': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStat,
                    request_deserializer=api__pb2.ListStatRequest.FromString,
                    response_serializer=api__pb2.ListStatResponse.SerializeToString,
            ),
            'ListHist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHist,
                    request_deserializer=api__pb2.ListHistRequest.FromString,
                    response_serializer=api__pb2.ListHistResponse.SerializeToString,
            ),
            'getPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.getPrice,
                    request_deserializer=api__pb2.PriceRequest.FromString,
                    response_serializer=api__pb2.PriceResponse.SerializeToString,
            ),
            'getStaticData': grpc.unary_unary_rpc_method_handler(
                    servicer.getStaticData,
                    request_deserializer=api__pb2.StaticDataRequest.FromString,
                    response_serializer=api__pb2.StaticDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.API/ListNames',
            api__pb2.ListNamesRequest.SerializeToString,
            api__pb2.ListNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.API/ListStat',
            api__pb2.ListStatRequest.SerializeToString,
            api__pb2.ListStatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListHist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.API/ListHist',
            api__pb2.ListHistRequest.SerializeToString,
            api__pb2.ListHistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.API/getPrice',
            api__pb2.PriceRequest.SerializeToString,
            api__pb2.PriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getStaticData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.API/getStaticData',
            api__pb2.StaticDataRequest.SerializeToString,
            api__pb2.StaticDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
