# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataService_pb2 as dataService__pb2


class DATAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNames = channel.unary_unary(
                '/pb.DATA/getNames',
                request_serializer=dataService__pb2.NamesRequest.SerializeToString,
                response_deserializer=dataService__pb2.NamesResponse.FromString,
                )
        self.getStat = channel.unary_unary(
                '/pb.DATA/getStat',
                request_serializer=dataService__pb2.StatRequest.SerializeToString,
                response_deserializer=dataService__pb2.StatResponse.FromString,
                )
        self.getHist = channel.unary_unary(
                '/pb.DATA/getHist',
                request_serializer=dataService__pb2.HistRequest.SerializeToString,
                response_deserializer=dataService__pb2.HistResponse.FromString,
                )
        self.Price = channel.unary_unary(
                '/pb.DATA/Price',
                request_serializer=dataService__pb2.PriceDataRequest.SerializeToString,
                response_deserializer=dataService__pb2.PriceDataResponse.FromString,
                )
        self.Stat = channel.unary_unary(
                '/pb.DATA/Stat',
                request_serializer=dataService__pb2.StatDataRequest.SerializeToString,
                response_deserializer=dataService__pb2.StatDataResponse.FromString,
                )


class DATAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getHist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DATAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNames': grpc.unary_unary_rpc_method_handler(
                    servicer.getNames,
                    request_deserializer=dataService__pb2.NamesRequest.FromString,
                    response_serializer=dataService__pb2.NamesResponse.SerializeToString,
            ),
            'getStat': grpc.unary_unary_rpc_method_handler(
                    servicer.getStat,
                    request_deserializer=dataService__pb2.StatRequest.FromString,
                    response_serializer=dataService__pb2.StatResponse.SerializeToString,
            ),
            'getHist': grpc.unary_unary_rpc_method_handler(
                    servicer.getHist,
                    request_deserializer=dataService__pb2.HistRequest.FromString,
                    response_serializer=dataService__pb2.HistResponse.SerializeToString,
            ),
            'Price': grpc.unary_unary_rpc_method_handler(
                    servicer.Price,
                    request_deserializer=dataService__pb2.PriceDataRequest.FromString,
                    response_serializer=dataService__pb2.PriceDataResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=dataService__pb2.StatDataRequest.FromString,
                    response_serializer=dataService__pb2.StatDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.DATA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DATA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.DATA/getNames',
            dataService__pb2.NamesRequest.SerializeToString,
            dataService__pb2.NamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.DATA/getStat',
            dataService__pb2.StatRequest.SerializeToString,
            dataService__pb2.StatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getHist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.DATA/getHist',
            dataService__pb2.HistRequest.SerializeToString,
            dataService__pb2.HistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.DATA/Price',
            dataService__pb2.PriceDataRequest.SerializeToString,
            dataService__pb2.PriceDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.DATA/Stat',
            dataService__pb2.StatDataRequest.SerializeToString,
            dataService__pb2.StatDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
