// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/dataService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DATAClient is the client API for DATA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DATAClient interface {
	GetNames(ctx context.Context, in *NamesRequest, opts ...grpc.CallOption) (*NamesResponse, error)
	GetStat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	GetHist(ctx context.Context, in *HistRequest, opts ...grpc.CallOption) (*HistResponse, error)
	Price(ctx context.Context, in *PriceDataRequest, opts ...grpc.CallOption) (*PriceDataResponse, error)
	Stat(ctx context.Context, in *StatDataRequest, opts ...grpc.CallOption) (*StatDataResponse, error)
}

type dATAClient struct {
	cc grpc.ClientConnInterface
}

func NewDATAClient(cc grpc.ClientConnInterface) DATAClient {
	return &dATAClient{cc}
}

func (c *dATAClient) GetNames(ctx context.Context, in *NamesRequest, opts ...grpc.CallOption) (*NamesResponse, error) {
	out := new(NamesResponse)
	err := c.cc.Invoke(ctx, "/pb.DATA/getNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dATAClient) GetStat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, "/pb.DATA/getStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dATAClient) GetHist(ctx context.Context, in *HistRequest, opts ...grpc.CallOption) (*HistResponse, error) {
	out := new(HistResponse)
	err := c.cc.Invoke(ctx, "/pb.DATA/getHist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dATAClient) Price(ctx context.Context, in *PriceDataRequest, opts ...grpc.CallOption) (*PriceDataResponse, error) {
	out := new(PriceDataResponse)
	err := c.cc.Invoke(ctx, "/pb.DATA/Price", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dATAClient) Stat(ctx context.Context, in *StatDataRequest, opts ...grpc.CallOption) (*StatDataResponse, error) {
	out := new(StatDataResponse)
	err := c.cc.Invoke(ctx, "/pb.DATA/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DATAServer is the server API for DATA service.
// All implementations must embed UnimplementedDATAServer
// for forward compatibility
type DATAServer interface {
	GetNames(context.Context, *NamesRequest) (*NamesResponse, error)
	GetStat(context.Context, *StatRequest) (*StatResponse, error)
	GetHist(context.Context, *HistRequest) (*HistResponse, error)
	Price(context.Context, *PriceDataRequest) (*PriceDataResponse, error)
	Stat(context.Context, *StatDataRequest) (*StatDataResponse, error)
	mustEmbedUnimplementedDATAServer()
}

// UnimplementedDATAServer must be embedded to have forward compatible implementations.
type UnimplementedDATAServer struct {
}

func (UnimplementedDATAServer) GetNames(context.Context, *NamesRequest) (*NamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNames not implemented")
}
func (UnimplementedDATAServer) GetStat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStat not implemented")
}
func (UnimplementedDATAServer) GetHist(context.Context, *HistRequest) (*HistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHist not implemented")
}
func (UnimplementedDATAServer) Price(context.Context, *PriceDataRequest) (*PriceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Price not implemented")
}
func (UnimplementedDATAServer) Stat(context.Context, *StatDataRequest) (*StatDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedDATAServer) mustEmbedUnimplementedDATAServer() {}

// UnsafeDATAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DATAServer will
// result in compilation errors.
type UnsafeDATAServer interface {
	mustEmbedUnimplementedDATAServer()
}

func RegisterDATAServer(s grpc.ServiceRegistrar, srv DATAServer) {
	s.RegisterService(&DATA_ServiceDesc, srv)
}

func _DATA_GetNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DATAServer).GetNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DATA/getNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DATAServer).GetNames(ctx, req.(*NamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DATA_GetStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DATAServer).GetStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DATA/getStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DATAServer).GetStat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DATA_GetHist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DATAServer).GetHist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DATA/getHist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DATAServer).GetHist(ctx, req.(*HistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DATA_Price_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DATAServer).Price(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DATA/Price",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DATAServer).Price(ctx, req.(*PriceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DATA_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DATAServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DATA/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DATAServer).Stat(ctx, req.(*StatDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DATA_ServiceDesc is the grpc.ServiceDesc for DATA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DATA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DATA",
	HandlerType: (*DATAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNames",
			Handler:    _DATA_GetNames_Handler,
		},
		{
			MethodName: "getStat",
			Handler:    _DATA_GetStat_Handler,
		},
		{
			MethodName: "getHist",
			Handler:    _DATA_GetHist_Handler,
		},
		{
			MethodName: "Price",
			Handler:    _DATA_Price_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _DATA_Stat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dataService.proto",
}
