// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1
// source: proto/dataService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumericalFilter int32

const (
	NumericalFilter_ltDS NumericalFilter = 0
	NumericalFilter_gtDS NumericalFilter = 1
)

// Enum value maps for NumericalFilter.
var (
	NumericalFilter_name = map[int32]string{
		0: "ltDS",
		1: "gtDS",
	}
	NumericalFilter_value = map[string]int32{
		"ltDS": 0,
		"gtDS": 1,
	}
)

func (x NumericalFilter) Enum() *NumericalFilter {
	p := new(NumericalFilter)
	*p = x
	return p
}

func (x NumericalFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericalFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dataService_proto_enumTypes[0].Descriptor()
}

func (NumericalFilter) Type() protoreflect.EnumType {
	return &file_proto_dataService_proto_enumTypes[0]
}

func (x NumericalFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericalFilter.Descriptor instead.
func (NumericalFilter) EnumDescriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{0}
}

type Property int32

const (
	Property_volumeDS    Property = 0
	Property_marketCapDS Property = 1
	Property_openDS      Property = 2
	Property_closeDS     Property = 3
	Property_highDS      Property = 4
	Property_lowDS       Property = 5
)

// Enum value maps for Property.
var (
	Property_name = map[int32]string{
		0: "volumeDS",
		1: "marketCapDS",
		2: "openDS",
		3: "closeDS",
		4: "highDS",
		5: "lowDS",
	}
	Property_value = map[string]int32{
		"volumeDS":    0,
		"marketCapDS": 1,
		"openDS":      2,
		"closeDS":     3,
		"highDS":      4,
		"lowDS":       5,
	}
)

func (x Property) Enum() *Property {
	p := new(Property)
	*p = x
	return p
}

func (x Property) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Property) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dataService_proto_enumTypes[1].Descriptor()
}

func (Property) Type() protoreflect.EnumType {
	return &file_proto_dataService_proto_enumTypes[1]
}

func (x Property) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Property.Descriptor instead.
func (Property) EnumDescriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{1}
}

type NamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterDS *Filter `protobuf:"bytes,1,opt,name=filterDS,proto3" json:"filterDS,omitempty"`
}

func (x *NamesRequest) Reset() {
	*x = NamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamesRequest) ProtoMessage() {}

func (x *NamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamesRequest.ProtoReflect.Descriptor instead.
func (*NamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{0}
}

func (x *NamesRequest) GetFilterDS() *Filter {
	if x != nil {
		return x.FilterDS
	}
	return nil
}

type NamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameDS []string `protobuf:"bytes,1,rep,name=nameDS,proto3" json:"nameDS,omitempty"`
}

func (x *NamesResponse) Reset() {
	*x = NamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamesResponse) ProtoMessage() {}

func (x *NamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamesResponse.ProtoReflect.Descriptor instead.
func (*NamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{1}
}

func (x *NamesResponse) GetNameDS() []string {
	if x != nil {
		return x.NameDS
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterDS *Filter `protobuf:"bytes,1,opt,name=filterDS,proto3" json:"filterDS,omitempty"`
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{2}
}

func (x *StatRequest) GetFilterDS() *Filter {
	if x != nil {
		return x.FilterDS
	}
	return nil
}

type StatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameDS              []string `protobuf:"bytes,1,rep,name=nameDS,proto3" json:"nameDS,omitempty"`
	CirculatingSupplyDS []string `protobuf:"bytes,2,rep,name=circulatingSupplyDS,proto3" json:"circulatingSupplyDS,omitempty"`
	TotalSupplyDS       []string `protobuf:"bytes,3,rep,name=totalSupplyDS,proto3" json:"totalSupplyDS,omitempty"`
	MaxSupplyDS         []string `protobuf:"bytes,4,rep,name=maxSupplyDS,proto3" json:"maxSupplyDS,omitempty"`
	CommitsDS           []string `protobuf:"bytes,5,rep,name=commitsDS,proto3" json:"commitsDS,omitempty"`
	ForksDS             []string `protobuf:"bytes,6,rep,name=forksDS,proto3" json:"forksDS,omitempty"`
	StarsDS             []string `protobuf:"bytes,7,rep,name=starsDS,proto3" json:"starsDS,omitempty"`
	WatchingDS          []string `protobuf:"bytes,8,rep,name=watchingDS,proto3" json:"watchingDS,omitempty"`
	DateFirstListingDS  []string `protobuf:"bytes,9,rep,name=dateFirstListingDS,proto3" json:"dateFirstListingDS,omitempty"`
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{3}
}

func (x *StatResponse) GetNameDS() []string {
	if x != nil {
		return x.NameDS
	}
	return nil
}

func (x *StatResponse) GetCirculatingSupplyDS() []string {
	if x != nil {
		return x.CirculatingSupplyDS
	}
	return nil
}

func (x *StatResponse) GetTotalSupplyDS() []string {
	if x != nil {
		return x.TotalSupplyDS
	}
	return nil
}

func (x *StatResponse) GetMaxSupplyDS() []string {
	if x != nil {
		return x.MaxSupplyDS
	}
	return nil
}

func (x *StatResponse) GetCommitsDS() []string {
	if x != nil {
		return x.CommitsDS
	}
	return nil
}

func (x *StatResponse) GetForksDS() []string {
	if x != nil {
		return x.ForksDS
	}
	return nil
}

func (x *StatResponse) GetStarsDS() []string {
	if x != nil {
		return x.StarsDS
	}
	return nil
}

func (x *StatResponse) GetWatchingDS() []string {
	if x != nil {
		return x.WatchingDS
	}
	return nil
}

func (x *StatResponse) GetDateFirstListingDS() []string {
	if x != nil {
		return x.DateFirstListingDS
	}
	return nil
}

type HistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterDS    *Filter `protobuf:"bytes,2,opt,name=filterDS,proto3" json:"filterDS,omitempty"`
	StartDateDS string  `protobuf:"bytes,3,opt,name=startDateDS,proto3" json:"startDateDS,omitempty"`
	EndDateDS   string  `protobuf:"bytes,4,opt,name=endDateDS,proto3" json:"endDateDS,omitempty"`
}

func (x *HistRequest) Reset() {
	*x = HistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistRequest) ProtoMessage() {}

func (x *HistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistRequest.ProtoReflect.Descriptor instead.
func (*HistRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{4}
}

func (x *HistRequest) GetFilterDS() *Filter {
	if x != nil {
		return x.FilterDS
	}
	return nil
}

func (x *HistRequest) GetStartDateDS() string {
	if x != nil {
		return x.StartDateDS
	}
	return ""
}

func (x *HistRequest) GetEndDateDS() string {
	if x != nil {
		return x.EndDateDS
	}
	return ""
}

type ListOpenPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenPrice []float64 `protobuf:"fixed64,1,rep,packed,name=openPrice,proto3" json:"openPrice,omitempty"`
}

func (x *ListOpenPrice) Reset() {
	*x = ListOpenPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOpenPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenPrice) ProtoMessage() {}

func (x *ListOpenPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenPrice.ProtoReflect.Descriptor instead.
func (*ListOpenPrice) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{5}
}

func (x *ListOpenPrice) GetOpenPrice() []float64 {
	if x != nil {
		return x.OpenPrice
	}
	return nil
}

type ListClosePrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClosePrice []float64 `protobuf:"fixed64,1,rep,packed,name=closePrice,proto3" json:"closePrice,omitempty"`
}

func (x *ListClosePrice) Reset() {
	*x = ListClosePrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClosePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClosePrice) ProtoMessage() {}

func (x *ListClosePrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClosePrice.ProtoReflect.Descriptor instead.
func (*ListClosePrice) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{6}
}

func (x *ListClosePrice) GetClosePrice() []float64 {
	if x != nil {
		return x.ClosePrice
	}
	return nil
}

type ListHighPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HighPrice []float64 `protobuf:"fixed64,1,rep,packed,name=highPrice,proto3" json:"highPrice,omitempty"`
}

func (x *ListHighPrice) Reset() {
	*x = ListHighPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHighPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHighPrice) ProtoMessage() {}

func (x *ListHighPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHighPrice.ProtoReflect.Descriptor instead.
func (*ListHighPrice) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{7}
}

func (x *ListHighPrice) GetHighPrice() []float64 {
	if x != nil {
		return x.HighPrice
	}
	return nil
}

type ListLowPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowPrice []float64 `protobuf:"fixed64,1,rep,packed,name=lowPrice,proto3" json:"lowPrice,omitempty"`
}

func (x *ListLowPrice) Reset() {
	*x = ListLowPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLowPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLowPrice) ProtoMessage() {}

func (x *ListLowPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLowPrice.ProtoReflect.Descriptor instead.
func (*ListLowPrice) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{8}
}

func (x *ListLowPrice) GetLowPrice() []float64 {
	if x != nil {
		return x.LowPrice
	}
	return nil
}

type ListVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Volume []float64 `protobuf:"fixed64,1,rep,packed,name=volume,proto3" json:"volume,omitempty"`
}

func (x *ListVolume) Reset() {
	*x = ListVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolume) ProtoMessage() {}

func (x *ListVolume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolume.ProtoReflect.Descriptor instead.
func (*ListVolume) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{9}
}

func (x *ListVolume) GetVolume() []float64 {
	if x != nil {
		return x.Volume
	}
	return nil
}

type ListMarketCap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketCap []float64 `protobuf:"fixed64,1,rep,packed,name=marketCap,proto3" json:"marketCap,omitempty"`
}

func (x *ListMarketCap) Reset() {
	*x = ListMarketCap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMarketCap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketCap) ProtoMessage() {}

func (x *ListMarketCap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketCap.ProtoReflect.Descriptor instead.
func (*ListMarketCap) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{10}
}

func (x *ListMarketCap) GetMarketCap() []float64 {
	if x != nil {
		return x.MarketCap
	}
	return nil
}

type ListDates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date []string `protobuf:"bytes,1,rep,name=date,proto3" json:"date,omitempty"`
}

func (x *ListDates) Reset() {
	*x = ListDates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDates) ProtoMessage() {}

func (x *ListDates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDates.ProtoReflect.Descriptor instead.
func (*ListDates) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{11}
}

func (x *ListDates) GetDate() []string {
	if x != nil {
		return x.Date
	}
	return nil
}

type HistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameDS         []string          `protobuf:"bytes,1,rep,name=nameDS,proto3" json:"nameDS,omitempty"`
	ListOpenPrice  []*ListOpenPrice  `protobuf:"bytes,2,rep,name=listOpenPrice,proto3" json:"listOpenPrice,omitempty"`
	ListClosePrice []*ListClosePrice `protobuf:"bytes,3,rep,name=listClosePrice,proto3" json:"listClosePrice,omitempty"`
	ListHighPrice  []*ListHighPrice  `protobuf:"bytes,4,rep,name=listHighPrice,proto3" json:"listHighPrice,omitempty"`
	ListLowPrice   []*ListLowPrice   `protobuf:"bytes,5,rep,name=listLowPrice,proto3" json:"listLowPrice,omitempty"`
	VolumeDS       []*ListVolume     `protobuf:"bytes,6,rep,name=volumeDS,proto3" json:"volumeDS,omitempty"`
	MarketCapDS    []*ListMarketCap  `protobuf:"bytes,7,rep,name=marketCapDS,proto3" json:"marketCapDS,omitempty"`
	DateDS         []*ListDates      `protobuf:"bytes,8,rep,name=dateDS,proto3" json:"dateDS,omitempty"`
}

func (x *HistResponse) Reset() {
	*x = HistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistResponse) ProtoMessage() {}

func (x *HistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistResponse.ProtoReflect.Descriptor instead.
func (*HistResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{12}
}

func (x *HistResponse) GetNameDS() []string {
	if x != nil {
		return x.NameDS
	}
	return nil
}

func (x *HistResponse) GetListOpenPrice() []*ListOpenPrice {
	if x != nil {
		return x.ListOpenPrice
	}
	return nil
}

func (x *HistResponse) GetListClosePrice() []*ListClosePrice {
	if x != nil {
		return x.ListClosePrice
	}
	return nil
}

func (x *HistResponse) GetListHighPrice() []*ListHighPrice {
	if x != nil {
		return x.ListHighPrice
	}
	return nil
}

func (x *HistResponse) GetListLowPrice() []*ListLowPrice {
	if x != nil {
		return x.ListLowPrice
	}
	return nil
}

func (x *HistResponse) GetVolumeDS() []*ListVolume {
	if x != nil {
		return x.VolumeDS
	}
	return nil
}

func (x *HistResponse) GetMarketCapDS() []*ListMarketCap {
	if x != nil {
		return x.MarketCapDS
	}
	return nil
}

func (x *HistResponse) GetDateDS() []*ListDates {
	if x != nil {
		return x.DateDS
	}
	return nil
}

type PriceDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameDS      string `protobuf:"bytes,1,opt,name=nameDS,proto3" json:"nameDS,omitempty"`
	StartDateDS string `protobuf:"bytes,2,opt,name=startDateDS,proto3" json:"startDateDS,omitempty"`
	EndDateDS   string `protobuf:"bytes,3,opt,name=endDateDS,proto3" json:"endDateDS,omitempty"`
}

func (x *PriceDataRequest) Reset() {
	*x = PriceDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceDataRequest) ProtoMessage() {}

func (x *PriceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceDataRequest.ProtoReflect.Descriptor instead.
func (*PriceDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{13}
}

func (x *PriceDataRequest) GetNameDS() string {
	if x != nil {
		return x.NameDS
	}
	return ""
}

func (x *PriceDataRequest) GetStartDateDS() string {
	if x != nil {
		return x.StartDateDS
	}
	return ""
}

func (x *PriceDataRequest) GetEndDateDS() string {
	if x != nil {
		return x.EndDateDS
	}
	return ""
}

type PriceDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenDS      []float64 `protobuf:"fixed64,1,rep,packed,name=openDS,proto3" json:"openDS,omitempty"`
	CloseDS     []float64 `protobuf:"fixed64,2,rep,packed,name=closeDS,proto3" json:"closeDS,omitempty"`
	HighDS      []float64 `protobuf:"fixed64,3,rep,packed,name=highDS,proto3" json:"highDS,omitempty"`
	LowDS       []float64 `protobuf:"fixed64,4,rep,packed,name=lowDS,proto3" json:"lowDS,omitempty"`
	VolumeDS    []float64 `protobuf:"fixed64,5,rep,packed,name=volumeDS,proto3" json:"volumeDS,omitempty"`
	MarketcapDS []float64 `protobuf:"fixed64,6,rep,packed,name=marketcapDS,proto3" json:"marketcapDS,omitempty"`
	DateDS      []string  `protobuf:"bytes,7,rep,name=dateDS,proto3" json:"dateDS,omitempty"`
}

func (x *PriceDataResponse) Reset() {
	*x = PriceDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceDataResponse) ProtoMessage() {}

func (x *PriceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceDataResponse.ProtoReflect.Descriptor instead.
func (*PriceDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{14}
}

func (x *PriceDataResponse) GetOpenDS() []float64 {
	if x != nil {
		return x.OpenDS
	}
	return nil
}

func (x *PriceDataResponse) GetCloseDS() []float64 {
	if x != nil {
		return x.CloseDS
	}
	return nil
}

func (x *PriceDataResponse) GetHighDS() []float64 {
	if x != nil {
		return x.HighDS
	}
	return nil
}

func (x *PriceDataResponse) GetLowDS() []float64 {
	if x != nil {
		return x.LowDS
	}
	return nil
}

func (x *PriceDataResponse) GetVolumeDS() []float64 {
	if x != nil {
		return x.VolumeDS
	}
	return nil
}

func (x *PriceDataResponse) GetMarketcapDS() []float64 {
	if x != nil {
		return x.MarketcapDS
	}
	return nil
}

func (x *PriceDataResponse) GetDateDS() []string {
	if x != nil {
		return x.DateDS
	}
	return nil
}

type StatDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StatDataRequest) Reset() {
	*x = StatDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataRequest) ProtoMessage() {}

func (x *StatDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataRequest.ProtoReflect.Descriptor instead.
func (*StatDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{15}
}

func (x *StatDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CirculatingSupplyDS string  `protobuf:"bytes,1,opt,name=circulatingSupplyDS,proto3" json:"circulatingSupplyDS,omitempty"`
	TotalSupplyDS       string  `protobuf:"bytes,2,opt,name=totalSupplyDS,proto3" json:"totalSupplyDS,omitempty"`
	MaxSupplyDS         string  `protobuf:"bytes,3,opt,name=maxSupplyDS,proto3" json:"maxSupplyDS,omitempty"`
	DateFirstListingDS  string  `protobuf:"bytes,4,opt,name=dateFirstListingDS,proto3" json:"dateFirstListingDS,omitempty"`
	CommitsDS           *string `protobuf:"bytes,5,opt,name=commitsDS,proto3,oneof" json:"commitsDS,omitempty"`
	ForksDS             *string `protobuf:"bytes,6,opt,name=forksDS,proto3,oneof" json:"forksDS,omitempty"`
	StarsDS             *string `protobuf:"bytes,7,opt,name=starsDS,proto3,oneof" json:"starsDS,omitempty"`
	WatchingDS          *string `protobuf:"bytes,8,opt,name=watchingDS,proto3,oneof" json:"watchingDS,omitempty"`
}

func (x *StatDataResponse) Reset() {
	*x = StatDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataResponse) ProtoMessage() {}

func (x *StatDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataResponse.ProtoReflect.Descriptor instead.
func (*StatDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{16}
}

func (x *StatDataResponse) GetCirculatingSupplyDS() string {
	if x != nil {
		return x.CirculatingSupplyDS
	}
	return ""
}

func (x *StatDataResponse) GetTotalSupplyDS() string {
	if x != nil {
		return x.TotalSupplyDS
	}
	return ""
}

func (x *StatDataResponse) GetMaxSupplyDS() string {
	if x != nil {
		return x.MaxSupplyDS
	}
	return ""
}

func (x *StatDataResponse) GetDateFirstListingDS() string {
	if x != nil {
		return x.DateFirstListingDS
	}
	return ""
}

func (x *StatDataResponse) GetCommitsDS() string {
	if x != nil && x.CommitsDS != nil {
		return *x.CommitsDS
	}
	return ""
}

func (x *StatDataResponse) GetForksDS() string {
	if x != nil && x.ForksDS != nil {
		return *x.ForksDS
	}
	return ""
}

func (x *StatDataResponse) GetStarsDS() string {
	if x != nil && x.StarsDS != nil {
		return *x.StarsDS
	}
	return ""
}

func (x *StatDataResponse) GetWatchingDS() string {
	if x != nil && x.WatchingDS != nil {
		return *x.WatchingDS
	}
	return ""
}

type CategoricalFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagDS string `protobuf:"bytes,1,opt,name=tagDS,proto3" json:"tagDS,omitempty"`
}

func (x *CategoricalFilters) Reset() {
	*x = CategoricalFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoricalFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoricalFilters) ProtoMessage() {}

func (x *CategoricalFilters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoricalFilters.ProtoReflect.Descriptor instead.
func (*CategoricalFilters) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{17}
}

func (x *CategoricalFilters) GetTagDS() string {
	if x != nil {
		return x.TagDS
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumfilterDS  []NumericalFilter     `protobuf:"varint,1,rep,packed,name=numfilterDS,proto3,enum=pb.NumericalFilter" json:"numfilterDS,omitempty"`
	CatfilterDS  []*CategoricalFilters `protobuf:"bytes,2,rep,name=catfilterDS,proto3" json:"catfilterDS,omitempty"`
	PropertiesDS []Property            `protobuf:"varint,3,rep,packed,name=propertiesDS,proto3,enum=pb.Property" json:"propertiesDS,omitempty"`
	ValuesDS     []float64             `protobuf:"fixed64,4,rep,packed,name=valuesDS,proto3" json:"valuesDS,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataService_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataService_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_dataService_proto_rawDescGZIP(), []int{18}
}

func (x *Filter) GetNumfilterDS() []NumericalFilter {
	if x != nil {
		return x.NumfilterDS
	}
	return nil
}

func (x *Filter) GetCatfilterDS() []*CategoricalFilters {
	if x != nil {
		return x.CatfilterDS
	}
	return nil
}

func (x *Filter) GetPropertiesDS() []Property {
	if x != nil {
		return x.PropertiesDS
	}
	return nil
}

func (x *Filter) GetValuesDS() []float64 {
	if x != nil {
		return x.ValuesDS
	}
	return nil
}

var File_proto_dataService_proto protoreflect.FileDescriptor

var file_proto_dataService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x36, 0x0a,
	0x0c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x44, 0x53, 0x22, 0x27, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x22, 0x35,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x44, 0x53, 0x22, 0xc2, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x12, 0x30,
	0x0a, 0x13, 0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70,
	0x70, 0x6c, 0x79, 0x44, 0x53, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x63, 0x69, 0x72,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x53,
	0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44,
	0x53, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x44, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x75, 0x70,
	0x70, 0x6c, 0x79, 0x44, 0x53, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x78,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x53, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x73, 0x44, 0x53, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x73, 0x44, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6b, 0x73, 0x44,
	0x53, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x6b, 0x73, 0x44, 0x53,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x73, 0x44, 0x53, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x73, 0x44, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x12, 0x2e, 0x0a, 0x12, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x53,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x22, 0x75, 0x0a, 0x0b, 0x48, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x44, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44,
	0x53, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x44, 0x53,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x44, 0x53, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x44, 0x53,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x44,
	0x53, 0x22, 0x2d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x30, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x67, 0x68, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x68, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x24, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x43, 0x61, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x22, 0x1f, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x92, 0x03, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x12, 0x37, 0x0a, 0x0d,
	0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x37, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x6c, 0x69, 0x73,
	0x74, 0x48, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x6c, 0x69,
	0x73, 0x74, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x53, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x53, 0x12, 0x33, 0x0a, 0x0b,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x44, 0x53, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x43, 0x61, 0x70, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x44,
	0x53, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x44, 0x53, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x44, 0x53, 0x22, 0x6a, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61,
	0x6d, 0x65, 0x44, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x44, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x44, 0x61, 0x74, 0x65, 0x44, 0x53, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x44, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x44, 0x53, 0x22, 0xc9, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x69, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x44, 0x53, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x44, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x53, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x07, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x53, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x69, 0x67, 0x68, 0x44, 0x53, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x68, 0x69,
	0x67, 0x68, 0x44, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x77, 0x44, 0x53, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x6f, 0x77, 0x44, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x44, 0x53, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x44, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x63, 0x61, 0x70, 0x44, 0x53, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x63, 0x61, 0x70, 0x44, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x53, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x44, 0x53,
	0x22, 0x25, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xf7, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x13,
	0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x44, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x69, 0x72, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x53, 0x12, 0x24,
	0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x53, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x44, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x44, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x44, 0x53, 0x12, 0x2e, 0x0a, 0x12, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x12, 0x21, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x73, 0x44, 0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x73, 0x44, 0x53, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x6f, 0x72,
	0x6b, 0x73, 0x44, 0x53, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x66, 0x6f,
	0x72, 0x6b, 0x73, 0x44, 0x53, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x73, 0x44, 0x53, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x73, 0x44, 0x53, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x44, 0x53, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0a, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x44, 0x53, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x44, 0x53, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x66,
	0x6f, 0x72, 0x6b, 0x73, 0x44, 0x53, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x73,
	0x44, 0x53, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x44,
	0x53, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x44, 0x53,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x44, 0x53, 0x22, 0xc7, 0x01,
	0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x12,
	0x38, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0b, 0x63, 0x61,
	0x74, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x53, 0x12, 0x30, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x44, 0x53, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x0c, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x44, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x44, 0x53, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x44, 0x53, 0x2a, 0x25, 0x0a, 0x0f, 0x4e, 0x75, 0x6d, 0x65, 0x72,
	0x69, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x74,
	0x44, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x67, 0x74, 0x44, 0x53, 0x10, 0x01, 0x2a, 0x59,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x08, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x44, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x44, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x70, 0x65,
	0x6e, 0x44, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x53,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x68, 0x69, 0x67, 0x68, 0x44, 0x53, 0x10, 0x04, 0x12, 0x09,
	0x0a, 0x05, 0x6c, 0x6f, 0x77, 0x44, 0x53, 0x10, 0x05, 0x32, 0x86, 0x02, 0x0a, 0x04, 0x44, 0x41,
	0x54, 0x41, 0x12, 0x31, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_dataService_proto_rawDescOnce sync.Once
	file_proto_dataService_proto_rawDescData = file_proto_dataService_proto_rawDesc
)

func file_proto_dataService_proto_rawDescGZIP() []byte {
	file_proto_dataService_proto_rawDescOnce.Do(func() {
		file_proto_dataService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dataService_proto_rawDescData)
	})
	return file_proto_dataService_proto_rawDescData
}

var file_proto_dataService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_dataService_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_dataService_proto_goTypes = []interface{}{
	(NumericalFilter)(0),       // 0: pb.NumericalFilter
	(Property)(0),              // 1: pb.Property
	(*NamesRequest)(nil),       // 2: pb.NamesRequest
	(*NamesResponse)(nil),      // 3: pb.NamesResponse
	(*StatRequest)(nil),        // 4: pb.StatRequest
	(*StatResponse)(nil),       // 5: pb.StatResponse
	(*HistRequest)(nil),        // 6: pb.HistRequest
	(*ListOpenPrice)(nil),      // 7: pb.ListOpenPrice
	(*ListClosePrice)(nil),     // 8: pb.ListClosePrice
	(*ListHighPrice)(nil),      // 9: pb.ListHighPrice
	(*ListLowPrice)(nil),       // 10: pb.ListLowPrice
	(*ListVolume)(nil),         // 11: pb.ListVolume
	(*ListMarketCap)(nil),      // 12: pb.ListMarketCap
	(*ListDates)(nil),          // 13: pb.ListDates
	(*HistResponse)(nil),       // 14: pb.HistResponse
	(*PriceDataRequest)(nil),   // 15: pb.PriceDataRequest
	(*PriceDataResponse)(nil),  // 16: pb.PriceDataResponse
	(*StatDataRequest)(nil),    // 17: pb.StatDataRequest
	(*StatDataResponse)(nil),   // 18: pb.StatDataResponse
	(*CategoricalFilters)(nil), // 19: pb.CategoricalFilters
	(*Filter)(nil),             // 20: pb.Filter
}
var file_proto_dataService_proto_depIdxs = []int32{
	20, // 0: pb.NamesRequest.filterDS:type_name -> pb.Filter
	20, // 1: pb.StatRequest.filterDS:type_name -> pb.Filter
	20, // 2: pb.HistRequest.filterDS:type_name -> pb.Filter
	7,  // 3: pb.HistResponse.listOpenPrice:type_name -> pb.ListOpenPrice
	8,  // 4: pb.HistResponse.listClosePrice:type_name -> pb.ListClosePrice
	9,  // 5: pb.HistResponse.listHighPrice:type_name -> pb.ListHighPrice
	10, // 6: pb.HistResponse.listLowPrice:type_name -> pb.ListLowPrice
	11, // 7: pb.HistResponse.volumeDS:type_name -> pb.ListVolume
	12, // 8: pb.HistResponse.marketCapDS:type_name -> pb.ListMarketCap
	13, // 9: pb.HistResponse.dateDS:type_name -> pb.ListDates
	0,  // 10: pb.Filter.numfilterDS:type_name -> pb.NumericalFilter
	19, // 11: pb.Filter.catfilterDS:type_name -> pb.CategoricalFilters
	1,  // 12: pb.Filter.propertiesDS:type_name -> pb.Property
	2,  // 13: pb.DATA.getNames:input_type -> pb.NamesRequest
	4,  // 14: pb.DATA.getStat:input_type -> pb.StatRequest
	6,  // 15: pb.DATA.getHist:input_type -> pb.HistRequest
	15, // 16: pb.DATA.Price:input_type -> pb.PriceDataRequest
	17, // 17: pb.DATA.Stat:input_type -> pb.StatDataRequest
	3,  // 18: pb.DATA.getNames:output_type -> pb.NamesResponse
	5,  // 19: pb.DATA.getStat:output_type -> pb.StatResponse
	14, // 20: pb.DATA.getHist:output_type -> pb.HistResponse
	16, // 21: pb.DATA.Price:output_type -> pb.PriceDataResponse
	18, // 22: pb.DATA.Stat:output_type -> pb.StatDataResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_dataService_proto_init() }
func file_proto_dataService_proto_init() {
	if File_proto_dataService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dataService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOpenPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClosePrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHighPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLowPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMarketCap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoricalFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataService_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_dataService_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dataService_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dataService_proto_goTypes,
		DependencyIndexes: file_proto_dataService_proto_depIdxs,
		EnumInfos:         file_proto_dataService_proto_enumTypes,
		MessageInfos:      file_proto_dataService_proto_msgTypes,
	}.Build()
	File_proto_dataService_proto = out.File
	file_proto_dataService_proto_rawDesc = nil
	file_proto_dataService_proto_goTypes = nil
	file_proto_dataService_proto_depIdxs = nil
}
