// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1
// source: proto/api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyApi int32

const (
	PropertyApi_volume    PropertyApi = 0
	PropertyApi_marketCap PropertyApi = 1
	PropertyApi_open      PropertyApi = 2
	PropertyApi_close     PropertyApi = 3
	PropertyApi_high      PropertyApi = 4
	PropertyApi_low       PropertyApi = 5
)

// Enum value maps for PropertyApi.
var (
	PropertyApi_name = map[int32]string{
		0: "volume",
		1: "marketCap",
		2: "open",
		3: "close",
		4: "high",
		5: "low",
	}
	PropertyApi_value = map[string]int32{
		"volume":    0,
		"marketCap": 1,
		"open":      2,
		"close":     3,
		"high":      4,
		"low":       5,
	}
)

func (x PropertyApi) Enum() *PropertyApi {
	p := new(PropertyApi)
	*p = x
	return p
}

func (x PropertyApi) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyApi) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (PropertyApi) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x PropertyApi) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyApi.Descriptor instead.
func (PropertyApi) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type NumericalFilterApi int32

const (
	NumericalFilterApi_lt NumericalFilterApi = 0
	NumericalFilterApi_gt NumericalFilterApi = 1
)

// Enum value maps for NumericalFilterApi.
var (
	NumericalFilterApi_name = map[int32]string{
		0: "lt",
		1: "gt",
	}
	NumericalFilterApi_value = map[string]int32{
		"lt": 0,
		"gt": 1,
	}
)

func (x NumericalFilterApi) Enum() *NumericalFilterApi {
	p := new(NumericalFilterApi)
	*p = x
	return p
}

func (x NumericalFilterApi) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericalFilterApi) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[1].Descriptor()
}

func (NumericalFilterApi) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[1]
}

func (x NumericalFilterApi) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericalFilterApi.Descriptor instead.
func (NumericalFilterApi) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

type ListNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterApi *FilterApi `protobuf:"bytes,1,opt,name=filterApi,proto3" json:"filterApi,omitempty"`
}

func (x *ListNamesRequest) Reset() {
	*x = ListNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesRequest) ProtoMessage() {}

func (x *ListNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesRequest.ProtoReflect.Descriptor instead.
func (*ListNamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListNamesRequest) GetFilterApi() *FilterApi {
	if x != nil {
		return x.FilterApi
	}
	return nil
}

type ListNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *ListNamesResponse) Reset() {
	*x = ListNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesResponse) ProtoMessage() {}

func (x *ListNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesResponse.ProtoReflect.Descriptor instead.
func (*ListNamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListNamesResponse) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type ListStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterApi *FilterApi `protobuf:"bytes,1,opt,name=FilterApi,proto3" json:"FilterApi,omitempty"`
}

func (x *ListStatRequest) Reset() {
	*x = ListStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatRequest) ProtoMessage() {}

func (x *ListStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatRequest.ProtoReflect.Descriptor instead.
func (*ListStatRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListStatRequest) GetFilterApi() *FilterApi {
	if x != nil {
		return x.FilterApi
	}
	return nil
}

type ListStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameApi              []string `protobuf:"bytes,1,rep,name=nameApi,proto3" json:"nameApi,omitempty"`
	DateFirstListingApi  []string `protobuf:"bytes,2,rep,name=dateFirstListingApi,proto3" json:"dateFirstListingApi,omitempty"`
	CommitsApi           []string `protobuf:"bytes,3,rep,name=commitsApi,proto3" json:"commitsApi,omitempty"`
	ForksApi             []string `protobuf:"bytes,4,rep,name=forksApi,proto3" json:"forksApi,omitempty"`
	StartsApi            []string `protobuf:"bytes,5,rep,name=startsApi,proto3" json:"startsApi,omitempty"`
	WatchingApi          []string `protobuf:"bytes,6,rep,name=watchingApi,proto3" json:"watchingApi,omitempty"`
	CirculatingSupplyApi []string `protobuf:"bytes,7,rep,name=circulatingSupplyApi,proto3" json:"circulatingSupplyApi,omitempty"`
	TotalSupplyApi       []string `protobuf:"bytes,8,rep,name=totalSupplyApi,proto3" json:"totalSupplyApi,omitempty"`
	MaxSupplyApi         []string `protobuf:"bytes,9,rep,name=maxSupplyApi,proto3" json:"maxSupplyApi,omitempty"`
}

func (x *ListStatResponse) Reset() {
	*x = ListStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatResponse) ProtoMessage() {}

func (x *ListStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatResponse.ProtoReflect.Descriptor instead.
func (*ListStatResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListStatResponse) GetNameApi() []string {
	if x != nil {
		return x.NameApi
	}
	return nil
}

func (x *ListStatResponse) GetDateFirstListingApi() []string {
	if x != nil {
		return x.DateFirstListingApi
	}
	return nil
}

func (x *ListStatResponse) GetCommitsApi() []string {
	if x != nil {
		return x.CommitsApi
	}
	return nil
}

func (x *ListStatResponse) GetForksApi() []string {
	if x != nil {
		return x.ForksApi
	}
	return nil
}

func (x *ListStatResponse) GetStartsApi() []string {
	if x != nil {
		return x.StartsApi
	}
	return nil
}

func (x *ListStatResponse) GetWatchingApi() []string {
	if x != nil {
		return x.WatchingApi
	}
	return nil
}

func (x *ListStatResponse) GetCirculatingSupplyApi() []string {
	if x != nil {
		return x.CirculatingSupplyApi
	}
	return nil
}

func (x *ListStatResponse) GetTotalSupplyApi() []string {
	if x != nil {
		return x.TotalSupplyApi
	}
	return nil
}

func (x *ListStatResponse) GetMaxSupplyApi() []string {
	if x != nil {
		return x.MaxSupplyApi
	}
	return nil
}

type ListHistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterApi    *FilterApi `protobuf:"bytes,1,opt,name=filterApi,proto3" json:"filterApi,omitempty"`
	StartDateApi string     `protobuf:"bytes,2,opt,name=startDateApi,proto3" json:"startDateApi,omitempty"`
	EndDateApi   string     `protobuf:"bytes,3,opt,name=endDateApi,proto3" json:"endDateApi,omitempty"`
}

func (x *ListHistRequest) Reset() {
	*x = ListHistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistRequest) ProtoMessage() {}

func (x *ListHistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistRequest.ProtoReflect.Descriptor instead.
func (*ListHistRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListHistRequest) GetFilterApi() *FilterApi {
	if x != nil {
		return x.FilterApi
	}
	return nil
}

func (x *ListHistRequest) GetStartDateApi() string {
	if x != nil {
		return x.StartDateApi
	}
	return ""
}

func (x *ListHistRequest) GetEndDateApi() string {
	if x != nil {
		return x.EndDateApi
	}
	return ""
}

type ListHistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameApi      []string  `protobuf:"bytes,1,rep,name=nameApi,proto3" json:"nameApi,omitempty"`
	OpenApi      []float64 `protobuf:"fixed64,2,rep,packed,name=openApi,proto3" json:"openApi,omitempty"`
	CloseApi     []float64 `protobuf:"fixed64,3,rep,packed,name=closeApi,proto3" json:"closeApi,omitempty"`
	HighApi      []float64 `protobuf:"fixed64,4,rep,packed,name=highApi,proto3" json:"highApi,omitempty"`
	LowApi       []float64 `protobuf:"fixed64,5,rep,packed,name=lowApi,proto3" json:"lowApi,omitempty"`
	VolumeApi    []float64 `protobuf:"fixed64,6,rep,packed,name=volumeApi,proto3" json:"volumeApi,omitempty"`
	MarketCapApi []float64 `protobuf:"fixed64,7,rep,packed,name=marketCapApi,proto3" json:"marketCapApi,omitempty"`
	DateApi      []string  `protobuf:"bytes,8,rep,name=dateApi,proto3" json:"dateApi,omitempty"`
}

func (x *ListHistResponse) Reset() {
	*x = ListHistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistResponse) ProtoMessage() {}

func (x *ListHistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistResponse.ProtoReflect.Descriptor instead.
func (*ListHistResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListHistResponse) GetNameApi() []string {
	if x != nil {
		return x.NameApi
	}
	return nil
}

func (x *ListHistResponse) GetOpenApi() []float64 {
	if x != nil {
		return x.OpenApi
	}
	return nil
}

func (x *ListHistResponse) GetCloseApi() []float64 {
	if x != nil {
		return x.CloseApi
	}
	return nil
}

func (x *ListHistResponse) GetHighApi() []float64 {
	if x != nil {
		return x.HighApi
	}
	return nil
}

func (x *ListHistResponse) GetLowApi() []float64 {
	if x != nil {
		return x.LowApi
	}
	return nil
}

func (x *ListHistResponse) GetVolumeApi() []float64 {
	if x != nil {
		return x.VolumeApi
	}
	return nil
}

func (x *ListHistResponse) GetMarketCapApi() []float64 {
	if x != nil {
		return x.MarketCapApi
	}
	return nil
}

func (x *ListHistResponse) GetDateApi() []string {
	if x != nil {
		return x.DateApi
	}
	return nil
}

type PriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartDateGHist string `protobuf:"bytes,2,opt,name=startDateGHist,proto3" json:"startDateGHist,omitempty"`
	EndDateHist    string `protobuf:"bytes,3,opt,name=endDateHist,proto3" json:"endDateHist,omitempty"`
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *PriceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriceRequest) GetStartDateGHist() string {
	if x != nil {
		return x.StartDateGHist
	}
	return ""
}

func (x *PriceRequest) GetEndDateHist() string {
	if x != nil {
		return x.EndDateHist
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenPrice  []float64 `protobuf:"fixed64,1,rep,packed,name=openPrice,proto3" json:"openPrice,omitempty"`
	ClosePrice []float64 `protobuf:"fixed64,2,rep,packed,name=closePrice,proto3" json:"closePrice,omitempty"`
	HighPrice  []float64 `protobuf:"fixed64,3,rep,packed,name=highPrice,proto3" json:"highPrice,omitempty"`
	LowPrice   []float64 `protobuf:"fixed64,4,rep,packed,name=lowPrice,proto3" json:"lowPrice,omitempty"`
	Volume     []float64 `protobuf:"fixed64,5,rep,packed,name=volume,proto3" json:"volume,omitempty"`
	MarketCap  []float64 `protobuf:"fixed64,6,rep,packed,name=marketCap,proto3" json:"marketCap,omitempty"`
	DatePrice  []string  `protobuf:"bytes,7,rep,name=datePrice,proto3" json:"datePrice,omitempty"`
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *PriceResponse) GetOpenPrice() []float64 {
	if x != nil {
		return x.OpenPrice
	}
	return nil
}

func (x *PriceResponse) GetClosePrice() []float64 {
	if x != nil {
		return x.ClosePrice
	}
	return nil
}

func (x *PriceResponse) GetHighPrice() []float64 {
	if x != nil {
		return x.HighPrice
	}
	return nil
}

func (x *PriceResponse) GetLowPrice() []float64 {
	if x != nil {
		return x.LowPrice
	}
	return nil
}

func (x *PriceResponse) GetVolume() []float64 {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *PriceResponse) GetMarketCap() []float64 {
	if x != nil {
		return x.MarketCap
	}
	return nil
}

func (x *PriceResponse) GetDatePrice() []string {
	if x != nil {
		return x.DatePrice
	}
	return nil
}

type StaticDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StaticDataRequest) Reset() {
	*x = StaticDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDataRequest) ProtoMessage() {}

func (x *StaticDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDataRequest.ProtoReflect.Descriptor instead.
func (*StaticDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *StaticDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StaticDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CirculatingSupply string  `protobuf:"bytes,1,opt,name=circulatingSupply,proto3" json:"circulatingSupply,omitempty"`
	TotalSupply       string  `protobuf:"bytes,2,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`
	MaxSupply         string  `protobuf:"bytes,3,opt,name=maxSupply,proto3" json:"maxSupply,omitempty"`
	DateFirstListing  string  `protobuf:"bytes,4,opt,name=dateFirstListing,proto3" json:"dateFirstListing,omitempty"`
	Commits           *string `protobuf:"bytes,5,opt,name=commits,proto3,oneof" json:"commits,omitempty"`
	Forks             *string `protobuf:"bytes,6,opt,name=forks,proto3,oneof" json:"forks,omitempty"`
	Stars             *string `protobuf:"bytes,7,opt,name=stars,proto3,oneof" json:"stars,omitempty"`
	Watching          *string `protobuf:"bytes,8,opt,name=watching,proto3,oneof" json:"watching,omitempty"`
}

func (x *StaticDataResponse) Reset() {
	*x = StaticDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDataResponse) ProtoMessage() {}

func (x *StaticDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDataResponse.ProtoReflect.Descriptor instead.
func (*StaticDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *StaticDataResponse) GetCirculatingSupply() string {
	if x != nil {
		return x.CirculatingSupply
	}
	return ""
}

func (x *StaticDataResponse) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *StaticDataResponse) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *StaticDataResponse) GetDateFirstListing() string {
	if x != nil {
		return x.DateFirstListing
	}
	return ""
}

func (x *StaticDataResponse) GetCommits() string {
	if x != nil && x.Commits != nil {
		return *x.Commits
	}
	return ""
}

func (x *StaticDataResponse) GetForks() string {
	if x != nil && x.Forks != nil {
		return *x.Forks
	}
	return ""
}

func (x *StaticDataResponse) GetStars() string {
	if x != nil && x.Stars != nil {
		return *x.Stars
	}
	return ""
}

func (x *StaticDataResponse) GetWatching() string {
	if x != nil && x.Watching != nil {
		return *x.Watching
	}
	return ""
}

type FilterApi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumFilterApi  []NumericalFilterApi `protobuf:"varint,1,rep,packed,name=numFilterApi,proto3,enum=pb.NumericalFilterApi" json:"numFilterApi,omitempty"`
	Tag           []string             `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	PropertiesApi []PropertyApi        `protobuf:"varint,3,rep,packed,name=propertiesApi,proto3,enum=pb.PropertyApi" json:"propertiesApi,omitempty"`
	ValuesApi     []float64            `protobuf:"fixed64,4,rep,packed,name=valuesApi,proto3" json:"valuesApi,omitempty"`
}

func (x *FilterApi) Reset() {
	*x = FilterApi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterApi) ProtoMessage() {}

func (x *FilterApi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterApi.ProtoReflect.Descriptor instead.
func (*FilterApi) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *FilterApi) GetNumFilterApi() []NumericalFilterApi {
	if x != nil {
		return x.NumFilterApi
	}
	return nil
}

func (x *FilterApi) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *FilterApi) GetPropertiesApi() []PropertyApi {
	if x != nil {
		return x.PropertiesApi
	}
	return nil
}

func (x *FilterApi) GetValuesApi() []float64 {
	if x != nil {
		return x.ValuesApi
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

var file_proto_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x52, 0x09, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x3e, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x41, 0x70, 0x69, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x22,
	0xda, 0x02, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x12, 0x30,
	0x0a, 0x13, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x41, 0x70, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x41, 0x70, 0x69, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x41, 0x70, 0x69,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6b, 0x73, 0x41, 0x70, 0x69, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6b, 0x73, 0x41, 0x70, 0x69, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x70, 0x69, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x70, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69, 0x12, 0x32, 0x0a, 0x14,
	0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x41, 0x70, 0x69, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x63, 0x69, 0x72, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x69,
	0x12, 0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x41,
	0x70, 0x69, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x69, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x69, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x61, 0x78, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x69, 0x22, 0x82, 0x01, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x22, 0x0a,
	0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x41, 0x70, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x41, 0x70,
	0x69, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x41, 0x70, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x41, 0x70,
	0x69, 0x22, 0xf0, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x70,
	0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x70, 0x69,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x41, 0x70, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x41, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x67, 0x68, 0x41, 0x70,
	0x69, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x68, 0x69, 0x67, 0x68, 0x41, 0x70, 0x69,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x77, 0x41, 0x70, 0x69, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x06, 0x6c, 0x6f, 0x77, 0x41, 0x70, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x41, 0x70, 0x69, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x43, 0x61, 0x70, 0x41, 0x70, 0x69, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0c, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x41, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x70, 0x69, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x70, 0x69, 0x22, 0x6c, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x47, 0x48, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x47, 0x48, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x48, 0x69,
	0x73, 0x74, 0x22, 0xdb, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x68, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x27, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xd1, 0x02, 0x0a, 0x12, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x69, 0x72,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x2a,
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x66, 0x6f, 0x72,
	0x6b, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x6b,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x1f, 0x0a, 0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x03, 0x52, 0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x66, 0x6f, 0x72, 0x6b, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x73,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x22, 0xae, 0x01,
	0x0a, 0x09, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x3a, 0x0a, 0x0c, 0x6e,
	0x75, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x35, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x41, 0x70, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x41, 0x70,
	0x69, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x41, 0x70, 0x69,
	0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x41, 0x70, 0x69, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x41, 0x70, 0x69, 0x2a, 0x50,
	0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x41, 0x70, 0x69, 0x12, 0x0a, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x03, 0x12, 0x08, 0x0a,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x10, 0x05,
	0x2a, 0x24, 0x0a, 0x12, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x06, 0x0a, 0x02, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x67, 0x74, 0x10, 0x01, 0x32, 0xa8, 0x02, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x3a,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08,
	0x67, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData = file_proto_api_proto_rawDesc
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_proto_rawDescData)
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_api_proto_goTypes = []interface{}{
	(PropertyApi)(0),           // 0: pb.PropertyApi
	(NumericalFilterApi)(0),    // 1: pb.NumericalFilterApi
	(*ListNamesRequest)(nil),   // 2: pb.ListNamesRequest
	(*ListNamesResponse)(nil),  // 3: pb.ListNamesResponse
	(*ListStatRequest)(nil),    // 4: pb.ListStatRequest
	(*ListStatResponse)(nil),   // 5: pb.ListStatResponse
	(*ListHistRequest)(nil),    // 6: pb.ListHistRequest
	(*ListHistResponse)(nil),   // 7: pb.ListHistResponse
	(*PriceRequest)(nil),       // 8: pb.PriceRequest
	(*PriceResponse)(nil),      // 9: pb.PriceResponse
	(*StaticDataRequest)(nil),  // 10: pb.StaticDataRequest
	(*StaticDataResponse)(nil), // 11: pb.StaticDataResponse
	(*FilterApi)(nil),          // 12: pb.FilterApi
}
var file_proto_api_proto_depIdxs = []int32{
	12, // 0: pb.ListNamesRequest.filterApi:type_name -> pb.FilterApi
	12, // 1: pb.ListStatRequest.FilterApi:type_name -> pb.FilterApi
	12, // 2: pb.ListHistRequest.filterApi:type_name -> pb.FilterApi
	1,  // 3: pb.FilterApi.numFilterApi:type_name -> pb.NumericalFilterApi
	0,  // 4: pb.FilterApi.propertiesApi:type_name -> pb.PropertyApi
	2,  // 5: pb.API.ListNames:input_type -> pb.ListNamesRequest
	4,  // 6: pb.API.ListStat:input_type -> pb.ListStatRequest
	6,  // 7: pb.API.ListHist:input_type -> pb.ListHistRequest
	8,  // 8: pb.API.getPrice:input_type -> pb.PriceRequest
	10, // 9: pb.API.getStaticData:input_type -> pb.StaticDataRequest
	3,  // 10: pb.API.ListNames:output_type -> pb.ListNamesResponse
	5,  // 11: pb.API.ListStat:output_type -> pb.ListStatResponse
	7,  // 12: pb.API.ListHist:output_type -> pb.ListHistResponse
	9,  // 13: pb.API.getPrice:output_type -> pb.PriceResponse
	11, // 14: pb.API.getStaticData:output_type -> pb.StaticDataResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterApi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_api_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		EnumInfos:         file_proto_api_proto_enumTypes,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_rawDesc = nil
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	ListNames(ctx context.Context, in *ListNamesRequest, opts ...grpc.CallOption) (*ListNamesResponse, error)
	ListStat(ctx context.Context, in *ListStatRequest, opts ...grpc.CallOption) (*ListStatResponse, error)
	ListHist(ctx context.Context, in *ListHistRequest, opts ...grpc.CallOption) (*ListHistResponse, error)
	GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
	GetStaticData(ctx context.Context, in *StaticDataRequest, opts ...grpc.CallOption) (*StaticDataResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ListNames(ctx context.Context, in *ListNamesRequest, opts ...grpc.CallOption) (*ListNamesResponse, error) {
	out := new(ListNamesResponse)
	err := c.cc.Invoke(ctx, "/pb.API/ListNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListStat(ctx context.Context, in *ListStatRequest, opts ...grpc.CallOption) (*ListStatResponse, error) {
	out := new(ListStatResponse)
	err := c.cc.Invoke(ctx, "/pb.API/ListStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListHist(ctx context.Context, in *ListHistRequest, opts ...grpc.CallOption) (*ListHistResponse, error) {
	out := new(ListHistResponse)
	err := c.cc.Invoke(ctx, "/pb.API/ListHist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/pb.API/getPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetStaticData(ctx context.Context, in *StaticDataRequest, opts ...grpc.CallOption) (*StaticDataResponse, error) {
	out := new(StaticDataResponse)
	err := c.cc.Invoke(ctx, "/pb.API/getStaticData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	ListNames(context.Context, *ListNamesRequest) (*ListNamesResponse, error)
	ListStat(context.Context, *ListStatRequest) (*ListStatResponse, error)
	ListHist(context.Context, *ListHistRequest) (*ListHistResponse, error)
	GetPrice(context.Context, *PriceRequest) (*PriceResponse, error)
	GetStaticData(context.Context, *StaticDataRequest) (*StaticDataResponse, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) ListNames(context.Context, *ListNamesRequest) (*ListNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNames not implemented")
}
func (*UnimplementedAPIServer) ListStat(context.Context, *ListStatRequest) (*ListStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStat not implemented")
}
func (*UnimplementedAPIServer) ListHist(context.Context, *ListHistRequest) (*ListHistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHist not implemented")
}
func (*UnimplementedAPIServer) GetPrice(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (*UnimplementedAPIServer) GetStaticData(context.Context, *StaticDataRequest) (*StaticDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaticData not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_ListNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/ListNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListNames(ctx, req.(*ListNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/ListStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListStat(ctx, req.(*ListStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListHist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListHist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/ListHist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListHist(ctx, req.(*ListHistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetPrice(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetStaticData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetStaticData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/GetStaticData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetStaticData(ctx, req.(*StaticDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNames",
			Handler:    _API_ListNames_Handler,
		},
		{
			MethodName: "ListStat",
			Handler:    _API_ListStat_Handler,
		},
		{
			MethodName: "ListHist",
			Handler:    _API_ListHist_Handler,
		},
		{
			MethodName: "getPrice",
			Handler:    _API_GetPrice_Handler,
		},
		{
			MethodName: "getStaticData",
			Handler:    _API_GetStaticData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
